[package]
name = "shebang"
version = "0.1.1"
edition = "2021"

[profile.release]
opt-level = 2
codegen-units = 1
panic = "abort"
strip = "symbols"
lto = true

[[bin]]
name = "shebang"
path = "src/shebang.rs"

[[bin]]
name = "env"
path = "src/env.rs"
